from sqlalchemy.orm import Session
from database import SessionLocal, engine
from models import University, Base

def seed_universities():
    db = SessionLocal()
    # Create tables if they don't exist
    Base.metadata.create_all(bind=engine)

    universities = [
        # --- UNITED KINGDOM ---
        {
            "name": "University of Oxford",
            "country": "United Kingdom",
            "city": "Oxford",
            "ranking": 1,
            "programs": "Arts, Humanities, Law, Medicine, Sciences, Engineering",
            "tuition_fee_min": 35000,
            "tuition_fee_max": 50000,
            "living_cost_yearly": 15000,
            "scholarship_available": True,
            "min_gpa": 3.8,
            "min_ielts": 7.5,
            "acceptance_rate": 17,
            "description": "One of the oldest and most prestigious universities in the world.",
            "website": "https://www.ox.ac.uk"
        },
        {
            "name": "University of Cambridge",
            "country": "United Kingdom",
            "city": "Cambridge",
            "ranking": 2,
            "programs": "Mathematics, Physics, Engineering, Law, History",
            "tuition_fee_min": 33000,
            "tuition_fee_max": 48000,
            "living_cost_yearly": 14500,
            "scholarship_available": True,
            "min_gpa": 3.8,
            "min_ielts": 7.5,
            "acceptance_rate": 21,
            "description": "A world-leading research university with a rich history of academic excellence.",
            "website": "https://www.cam.ac.uk"
        },
        {
            "name": "Imperial College London",
            "country": "United Kingdom",
            "city": "London",
            "ranking": 6,
            "programs": "Engineering, Medicine, Science, Business",
            "tuition_fee_min": 32000,
            "tuition_fee_max": 45000,
            "living_cost_yearly": 18000,
            "scholarship_available": True,
            "min_gpa": 3.7,
            "min_ielts": 7.0,
            "acceptance_rate": 14,
            "description": "Consistently ranked among the top universities for science and technology.",
            "website": "https://www.imperial.ac.uk"
        },
        {
            "name": "University of Edinburgh",
            "country": "United Kingdom",
            "city": "Edinburgh",
            "ranking": 22,
            "programs": "Social Sciences, Arts, Law, Medicine, Informatics",
            "tuition_fee_min": 24000,
            "tuition_fee_max": 35000,
            "living_cost_yearly": 13000,
            "scholarship_available": True,
            "min_gpa": 3.5,
            "min_ielts": 6.5,
            "acceptance_rate": 33,
            "description": "A historic university offering a wide range of academic opportunities in the Scottish capital.",
            "website": "https://www.ed.ac.uk"
        },
        {
            "name": "University College London (UCL)",
            "country": "United Kingdom",
            "city": "London",
            "ranking": 9,
            "programs": "Architecture, Engineering, Law, Medicine, Computer Science",
            "tuition_fee_min": 28000,
            "tuition_fee_max": 42000,
            "living_cost_yearly": 17000,
            "scholarship_available": True,
            "min_gpa": 3.6,
            "min_ielts": 7.0,
            "acceptance_rate": 48,
            "description": "London's global university with world-class research and teaching.",
            "website": "https://www.ucl.ac.uk"
        },
        {
            "name": "King's College London",
            "country": "United Kingdom",
            "city": "London",
            "ranking": 35,
            "programs": "Law, Medicine, Humanities, Social Sciences",
            "tuition_fee_min": 26000,
            "tuition_fee_max": 38000,
            "living_cost_yearly": 16500,
            "scholarship_available": True,
            "min_gpa": 3.4,
            "min_ielts": 6.5,
            "acceptance_rate": 52,
            "description": "One of England's oldest and most prestigious universities.",
            "website": "https://www.kcl.ac.uk"
        },
        # --- UNITED STATES ---
        {
            "name": "Harvard University",
            "country": "United States",
            "city": "Cambridge, MA",
            "ranking": 4,
            "programs": "Law, Medicine, Business, Arts, Social Sciences",
            "tuition_fee_min": 55000,
            "tuition_fee_max": 65000,
            "living_cost_yearly": 20000,
            "scholarship_available": True,
            "min_gpa": 3.9,
            "min_ielts": 7.5,
            "acceptance_rate": 5,
            "description": "An Ivy League institution known for its global leadership and influence.",
            "website": "https://www.harvard.edu"
        },
        {
            "name": "Stanford University",
            "country": "United States",
            "city": "Stanford, CA",
            "ranking": 3,
            "programs": "Computer Science, Engineering, Entrepreneurship, Law",
            "tuition_fee_min": 58000,
            "tuition_fee_max": 62000,
            "living_cost_yearly": 22000,
            "scholarship_available": True,
            "min_gpa": 3.9,
            "min_ielts": 7.5,
            "acceptance_rate": 4,
            "description": "A hub for innovation and technology in the heart of Silicon Valley.",
            "website": "https://www.stanford.edu"
        },
        {
            "name": "MIT",
            "country": "United States",
            "city": "Cambridge, MA",
            "ranking": 5,
            "programs": "Engineering, Physics, AI, Robotics, Economics",
            "tuition_fee_min": 56000,
            "tuition_fee_max": 60000,
            "living_cost_yearly": 21000,
            "scholarship_available": True,
            "min_gpa": 3.9,
            "min_ielts": 7.5,
            "acceptance_rate": 7,
            "description": "World-renowned for its pioneering research in science and engineering.",
            "website": "https://www.mit.edu"
        },
        {
            "name": "NYU (New York University)",
            "country": "United States",
            "city": "New York",
            "ranking": 38,
            "programs": "Business, Film, Law, Media, Psychology",
            "tuition_fee_min": 53000,
            "tuition_fee_max": 58000,
            "living_cost_yearly": 25000,
            "scholarship_available": True,
            "min_gpa": 3.6,
            "min_ielts": 7.0,
            "acceptance_rate": 13,
            "description": "A global university with campuses in NYC, Abu Dhabi, and Shanghai.",
            "website": "https://www.nyu.edu"
        },
        {
            "name": "University of California, Berkeley",
            "country": "United States",
            "city": "Berkeley, CA",
            "ranking": 10,
            "programs": "Computer Science, Engineering, Business, Social Sciences",
            "tuition_fee_min": 45000,
            "tuition_fee_max": 52000,
            "living_cost_yearly": 20000,
            "scholarship_available": True,
            "min_gpa": 3.7,
            "min_ielts": 7.0,
            "acceptance_rate": 17,
            "description": "A leading public research university with a strong emphasis on innovation.",
            "website": "https://www.berkeley.edu"
        },
        {
            "name": "University of Chicago",
            "country": "United States",
            "city": "Chicago, IL",
            "ranking": 15,
            "programs": "Economics, Law, Medicine, Social Sciences",
            "tuition_fee_min": 60000,
            "tuition_fee_max": 65000,
            "living_cost_yearly": 19000,
            "scholarship_available": True,
            "min_gpa": 3.8,
            "min_ielts": 7.5,
            "acceptance_rate": 6,
            "description": "Known for rigorous academics and influential research.",
            "website": "https://www.uchicago.edu"
        },
        {
            "name": "Columbia University",
            "country": "United States",
            "city": "New York, NY",
            "ranking": 18,
            "programs": "Journalism, Business, Law, Engineering",
            "tuition_fee_min": 62000,
            "tuition_fee_max": 68000,
            "living_cost_yearly": 24000,
            "scholarship_available": True,
            "min_gpa": 3.8,
            "min_ielts": 7.5,
            "acceptance_rate": 6,
            "description": "An Ivy League university in the heart of New York City.",
            "website": "https://www.columbia.edu"
        },
        {
            "name": "University of Pennsylvania",
            "country": "United States",
            "city": "Philadelphia, PA",
            "ranking": 13,
            "programs": "Business (Wharton), Engineering, Medicine, Law",
            "tuition_fee_min": 61000,
            "tuition_fee_max": 66000,
            "living_cost_yearly": 18000,
            "scholarship_available": True,
            "min_gpa": 3.8,
            "min_ielts": 7.5,
            "acceptance_rate": 8,
            "description": "Home to the prestigious Wharton School of Business.",
            "website": "https://www.upenn.edu"
        },
        # --- CANADA ---
        {
            "name": "University of Toronto",
            "country": "Canada",
            "city": "Toronto",
            "ranking": 21,
            "programs": "Computer Science, Medicine, Arts, Engineering",
            "tuition_fee_min": 45000,
            "tuition_fee_max": 60000,
            "living_cost_yearly": 15000,
            "scholarship_available": True,
            "min_gpa": 3.6,
            "min_ielts": 7.0,
            "acceptance_rate": 43,
            "description": "Canada's top-ranked university with a vast array of programs.",
            "website": "https://www.utoronto.ca"
        },
        {
            "name": "University of British Columbia",
            "country": "Canada",
            "city": "Vancouver",
            "ranking": 34,
            "programs": "Science, Forestry, Arts, Business",
            "tuition_fee_min": 40000,
            "tuition_fee_max": 52000,
            "living_cost_yearly": 16000,
            "scholarship_available": True,
            "min_gpa": 3.5,
            "min_ielts": 6.5,
            "acceptance_rate": 50,
            "description": "Known for its beautiful campus and strong research output.",
            "website": "https://www.ubc.ca"
        },
        {
            "name": "McGill University",
            "country": "Canada",
            "city": "Montreal",
            "ranking": 31,
            "programs": "Medicine, Engineering, Science, Arts",
            "tuition_fee_min": 25000,
            "tuition_fee_max": 55000,
            "living_cost_yearly": 14000,
            "scholarship_available": True,
            "min_gpa": 3.6,
            "min_ielts": 7.0,
            "acceptance_rate": 46,
            "description": "A world-class research university in the vibrant city of Montreal.",
            "website": "https://www.mcgill.ca"
        },
        {
            "name": "University of Waterloo",
            "country": "Canada",
            "city": "Waterloo",
            "ranking": 149,
            "programs": "Computer Science, Engineering, Mathematics, Co-op Programs",
            "tuition_fee_min": 35000,
            "tuition_fee_max": 48000,
            "living_cost_yearly": 12000,
            "scholarship_available": True,
            "min_gpa": 3.5,
            "min_ielts": 6.5,
            "acceptance_rate": 53,
            "description": "Canada's innovation hub with the world's largest co-op program.",
            "website": "https://uwaterloo.ca"
        },
        # --- AUSTRALIA ---
        {
            "name": "University of Melbourne",
            "country": "Australia",
            "city": "Melbourne",
            "ranking": 14,
            "programs": "Business, Medicine, Engineering, Law",
            "tuition_fee_min": 35000,
            "tuition_fee_max": 48000,
            "living_cost_yearly": 25000,
            "scholarship_available": True,
            "min_gpa": 3.4,
            "min_ielts": 6.5,
            "acceptance_rate": 70,
            "description": "Australia's leading university with a focus on global impact.",
            "website": "https://www.unimelb.edu.au"
        },
        {
            "name": "University of Sydney",
            "country": "Australia",
            "city": "Sydney",
            "ranking": 19,
            "programs": "Law, Medicine, Arts, Science, Business",
            "tuition_fee_min": 38000,
            "tuition_fee_max": 50000,
            "living_cost_yearly": 28000,
            "scholarship_available": True,
            "min_gpa": 3.4,
            "min_ielts": 6.5,
            "acceptance_rate": 30,
            "description": "Australia's first university, known for its academic reputation and stunning campus.",
            "website": "https://www.sydney.edu.au"
        },
        {
            "name": "Australian National University",
            "country": "Australia",
            "city": "Canberra",
            "ranking": 27,
            "programs": "Political Science, International Relations, Science, Engineering",
            "tuition_fee_min": 36000,
            "tuition_fee_max": 47000,
            "living_cost_yearly": 22000,
            "scholarship_available": True,
            "min_gpa": 3.5,
            "min_ielts": 6.5,
            "acceptance_rate": 35,
            "description": "Australia's national research university located in the capital.",
            "website": "https://www.anu.edu.au"
        },
        # --- GERMANY ---
        {
            "name": "TU Munich (TUM)",
            "country": "Germany",
            "city": "Munich",
            "ranking": 37,
            "programs": "Engineering, Computer Science, Physics, Management",
            "tuition_fee_min": 0,
            "tuition_fee_max": 6000,
            "living_cost_yearly": 12000,
            "scholarship_available": False,
            "min_gpa": 3.3,
            "min_ielts": 6.5,
            "acceptance_rate": 8,
            "description": "One of Europe's top technical universities with very low tuition.",
            "website": "https://www.tum.de"
        },
        {
            "name": "Ludwig Maximilian University of Munich",
            "country": "Germany",
            "city": "Munich",
            "ranking": 59,
            "programs": "Medicine, Law, Humanities, Natural Sciences",
            "tuition_fee_min": 0,
            "tuition_fee_max": 3000,
            "living_cost_yearly": 11000,
            "scholarship_available": True,
            "min_gpa": 3.4,
            "min_ielts": 6.5,
            "acceptance_rate": 15,
            "description": "One of Germany's oldest and most prestigious universities.",
            "website": "https://www.lmu.de"
        },
        {
            "name": "Heidelberg University",
            "country": "Germany",
            "city": "Heidelberg",
            "ranking": 64,
            "programs": "Medicine, Law, Natural Sciences, Humanities",
            "tuition_fee_min": 0,
            "tuition_fee_max": 3500,
            "living_cost_yearly": 10000,
            "scholarship_available": True,
            "min_gpa": 3.3,
            "min_ielts": 6.5,
            "acceptance_rate": 18,
            "description": "Germany's oldest university with a strong research tradition.",
            "website": "https://www.uni-heidelberg.de"
        },
        # --- SWITZERLAND ---
        {
            "name": "ETH Zurich",
            "country": "Switzerland",
            "city": "Zurich",
            "ranking": 7,
            "programs": "Physics, Engineering, Computer Science, Mathematics",
            "tuition_fee_min": 1500,
            "tuition_fee_max": 2000,
            "living_cost_yearly": 25000,
            "scholarship_available": True,
            "min_gpa": 3.8,
            "min_ielts": 7.0,
            "acceptance_rate": 27,
            "description": "A leading technical university in continental Europe.",
            "website": "https://ethz.ch"
        },
        {
            "name": "EPFL (École Polytechnique Fédérale de Lausanne)",
            "country": "Switzerland",
            "city": "Lausanne",
            "ranking": 16,
            "programs": "Engineering, Computer Science, Life Sciences",
            "tuition_fee_min": 1500,
            "tuition_fee_max": 2000,
            "living_cost_yearly": 24000,
            "scholarship_available": True,
            "min_gpa": 3.7,
            "min_ielts": 7.0,
            "acceptance_rate": 12,
            "description": "Switzerland's premier technical university with cutting-edge research.",
            "website": "https://www.epfl.ch"
        },
        # --- JAPAN ---
        {
            "name": "University of Tokyo",
            "country": "Japan",
            "city": "Tokyo",
            "ranking": 28,
            "programs": "Science, Engineering, Law, Humanities",
            "tuition_fee_min": 5000,
            "tuition_fee_max": 8000,
            "living_cost_yearly": 15000,
            "scholarship_available": True,
            "min_gpa": 3.7,
            "min_ielts": 6.5,
            "acceptance_rate": 34,
            "description": "The top-ranked university in Japan for research and academia.",
            "website": "https://www.u-tokyo.ac.jp"
        },
        {
            "name": "Kyoto University",
            "country": "Japan",
            "city": "Kyoto",
            "ranking": 36,
            "programs": "Science, Engineering, Medicine, Humanities",
            "tuition_fee_min": 5000,
            "tuition_fee_max": 8000,
            "living_cost_yearly": 13000,
            "scholarship_available": True,
            "min_gpa": 3.6,
            "min_ielts": 6.5,
            "acceptance_rate": 38,
            "description": "Japan's second-oldest university with a strong research focus.",
            "website": "https://www.kyoto-u.ac.jp"
        },
        # --- SINGAPORE ---
        {
            "name": "National University of Singapore (NUS)",
            "country": "Singapore",
            "city": "Singapore",
            "ranking": 8,
            "programs": "Engineering, Computing, Business, Medicine",
            "tuition_fee_min": 30000,
            "tuition_fee_max": 50000,
            "living_cost_yearly": 10000,
            "scholarship_available": True,
            "min_gpa": 3.8,
            "min_ielts": 7.0,
            "acceptance_rate": 5,
            "description": "Consistently ranked as Asia's top university.",
            "website": "https://www.nus.edu.sg"
        },
        {
            "name": "Nanyang Technological University (NTU)",
            "country": "Singapore",
            "city": "Singapore",
            "ranking": 26,
            "programs": "Engineering, Business, Science, Communication",
            "tuition_fee_min": 28000,
            "tuition_fee_max": 48000,
            "living_cost_yearly": 9500,
            "scholarship_available": True,
            "min_gpa": 3.7,
            "min_ielts": 6.5,
            "acceptance_rate": 10,
            "description": "A young and research-intensive university in Singapore.",
            "website": "https://www.ntu.edu.sg"
        },
        # --- NETHERLANDS ---
        {
            "name": "University of Amsterdam",
            "country": "Netherlands",
            "city": "Amsterdam",
            "ranking": 61,
            "programs": "Communication, Psychology, Social Sciences, Arts",
            "tuition_fee_min": 10000,
            "tuition_fee_max": 20000,
            "living_cost_yearly": 12000,
            "scholarship_available": True,
            "min_gpa": 3.4,
            "min_ielts": 7.0,
            "acceptance_rate": 4,
            "description": "A research-led university in the heart of Amsterdam with deep cultural roots.",
            "website": "https://www.uva.nl"
        },
        {
            "name": "Delft University of Technology",
            "country": "Netherlands",
            "city": "Delft",
            "ranking": 57,
            "programs": "Engineering, Architecture, Applied Sciences",
            "tuition_fee_min": 12000,
            "tuition_fee_max": 18000,
            "living_cost_yearly": 11000,
            "scholarship_available": True,
            "min_gpa": 3.5,
            "min_ielts": 6.5,
            "acceptance_rate": 25,
            "description": "The Netherlands' leading technical university.",
            "website": "https://www.tudelft.nl"
        },
        # --- FRANCE ---
        {
            "name": "Sorbonne University",
            "country": "France",
            "city": "Paris",
            "ranking": 59,
            "programs": "Arts, Humanities, Science, Engineering, Medicine",
            "tuition_fee_min": 3000,
            "tuition_fee_max": 5000,
            "living_cost_yearly": 15000,
            "scholarship_available": True,
            "min_gpa": 3.5,
            "min_ielts": 6.5,
            "acceptance_rate": 20,
            "description": "A world-class university in the center of Paris, famous for its humanities.",
            "website": "https://www.sorbonne-universite.fr"
        },
        {
            "name": "École Polytechnique",
            "country": "France",
            "city": "Palaiseau",
            "ranking": 61,
            "programs": "Engineering, Mathematics, Physics, Computer Science",
            "tuition_fee_min": 0,
            "tuition_fee_max": 12000,
            "living_cost_yearly": 14000,
            "scholarship_available": True,
            "min_gpa": 3.7,
            "min_ielts": 6.5,
            "acceptance_rate": 8,
            "description": "France's leading engineering school with a strong research focus.",
            "website": "https://www.polytechnique.edu"
        },
        # --- SOUTH KOREA ---
        {
            "name": "Seoul National University",
            "country": "South Korea",
            "city": "Seoul",
            "ranking": 41,
            "programs": "Engineering, Business, Medicine, Humanities",
            "tuition_fee_min": 6000,
            "tuition_fee_max": 10000,
            "living_cost_yearly": 10000,
            "scholarship_available": True,
            "min_gpa": 3.6,
            "min_ielts": 6.5,
            "acceptance_rate": 20,
            "description": "South Korea's most prestigious university.",
            "website": "https://www.snu.ac.kr"
        },
        {
            "name": "KAIST (Korea Advanced Institute of Science and Technology)",
            "country": "South Korea",
            "city": "Daejeon",
            "ranking": 56,
            "programs": "Engineering, Computer Science, Natural Sciences",
            "tuition_fee_min": 0,
            "tuition_fee_max": 8000,
            "living_cost_yearly": 9000,
            "scholarship_available": True,
            "min_gpa": 3.5,
            "min_ielts": 6.5,
            "acceptance_rate": 15,
            "description": "South Korea's top science and technology university.",
            "website": "https://www.kaist.ac.kr"
        },
        # --- HONG KONG ---
        {
            "name": "University of Hong Kong (HKU)",
            "country": "Hong Kong",
            "city": "Hong Kong",
            "ranking": 26,
            "programs": "Business, Law, Medicine, Engineering",
            "tuition_fee_min": 18000,
            "tuition_fee_max": 32000,
            "living_cost_yearly": 12000,
            "scholarship_available": True,
            "min_gpa": 3.6,
            "min_ielts": 6.5,
            "acceptance_rate": 10,
            "description": "Hong Kong's oldest and most prestigious university.",
            "website": "https://www.hku.hk"
        },
        {
            "name": "Hong Kong University of Science and Technology (HKUST)",
            "country": "Hong Kong",
            "city": "Hong Kong",
            "ranking": 60,
            "programs": "Engineering, Business, Science",
            "tuition_fee_min": 16000,
            "tuition_fee_max": 30000,
            "living_cost_yearly": 11000,
            "scholarship_available": True,
            "min_gpa": 3.5,
            "min_ielts": 6.5,
            "acceptance_rate": 25,
            "description": "A young research university focused on science and technology.",
            "website": "https://www.ust.hk"
        },
        # --- IRELAND ---
        {
            "name": "Trinity College Dublin",
            "country": "Ireland",
            "city": "Dublin",
            "ranking": 98,
            "programs": "Computer Science, Business, Law, Humanities",
            "tuition_fee_min": 18000,
            "tuition_fee_max": 28000,
            "living_cost_yearly": 13000,
            "scholarship_available": True,
            "min_gpa": 3.4,
            "min_ielts": 6.5,
            "acceptance_rate": 35,
            "description": "Ireland's oldest university with a strong international reputation.",
            "website": "https://www.tcd.ie"
        },
        # --- NEW ZEALAND ---
        {
            "name": "University of Auckland",
            "country": "New Zealand",
            "city": "Auckland",
            "ranking": 87,
            "programs": "Engineering, Business, Medicine, Arts",
            "tuition_fee_min": 28000,
            "tuition_fee_max": 40000,
            "living_cost_yearly": 15000,
            "scholarship_available": True,
            "min_gpa": 3.3,
            "min_ielts": 6.5,
            "acceptance_rate": 45,
            "description": "New Zealand's largest and highest-ranked university.",
            "website": "https://www.auckland.ac.nz"
        },
        # --- SWEDEN ---
        {
            "name": "Lund University",
            "country": "Sweden",
            "city": "Lund",
            "ranking": 75,
            "programs": "Engineering, Science, Medicine, Humanities",
            "tuition_fee_min": 0,
            "tuition_fee_max": 15000,
            "living_cost_yearly": 11000,
            "scholarship_available": True,
            "min_gpa": 3.4,
            "min_ielts": 6.5,
            "acceptance_rate": 30,
            "description": "One of Scandinavia's largest and most prestigious universities.",
            "website": "https://www.lu.se"
        },
        {
            "name": "KTH Royal Institute of Technology",
            "country": "Sweden",
            "city": "Stockholm",
            "ranking": 89,
            "programs": "Engineering, Architecture, Technology",
            "tuition_fee_min": 0,
            "tuition_fee_max": 16000,
            "living_cost_yearly": 12000,
            "scholarship_available": True,
            "min_gpa": 3.5,
            "min_ielts": 6.5,
            "acceptance_rate": 35,
            "description": "Sweden's largest technical university.",
            "website": "https://www.kth.se"
        },
        # --- ITALY ---
        {
            "name": "Politecnico di Milano",
            "country": "Italy",
            "city": "Milan",
            "ranking": 123,
            "programs": "Engineering, Architecture, Design",
            "tuition_fee_min": 4000,
            "tuition_fee_max": 8000,
            "living_cost_yearly": 11000,
            "scholarship_available": True,
            "min_gpa": 3.3,
            "min_ielts": 6.0,
            "acceptance_rate": 40,
            "description": "Italy's leading technical university.",
            "website": "https://www.polimi.it"
        },
        # --- SPAIN ---
        {
            "name": "University of Barcelona",
            "country": "Spain",
            "city": "Barcelona",
            "ranking": 184,
            "programs": "Medicine, Humanities, Science, Social Sciences",
            "tuition_fee_min": 2000,
            "tuition_fee_max": 5000,
            "living_cost_yearly": 10000,
            "scholarship_available": True,
            "min_gpa": 3.2,
            "min_ielts": 6.0,
            "acceptance_rate": 50,
            "description": "Spain's top-ranked university with a rich history.",
            "website": "https://www.ub.edu"
        },
        # --- BELGIUM ---
        {
            "name": "KU Leuven",
            "country": "Belgium",
            "city": "Leuven",
            "ranking": 70,
            "programs": "Engineering, Medicine, Science, Humanities",
            "tuition_fee_min": 1000,
            "tuition_fee_max": 6000,
            "living_cost_yearly": 10000,
            "scholarship_available": True,
            "min_gpa": 3.4,
            "min_ielts": 6.5,
            "acceptance_rate": 30,
            "description": "Belgium's largest and highest-ranked university.",
            "website": "https://www.kuleuven.be"
        }
    ]

    for uni_data in universities:
        existing = db.query(University).filter(University.name == uni_data["name"]).first()
        if not existing:
            uni = University(**uni_data)
            db.add(uni)
        else:
            # Update existing data
            for key, value in uni_data.items():
                setattr(existing, key, value)
    
    db.commit()
    print(f"Successfully seeded {len(universities)} diverse universities.")
    db.close()

if __name__ == "__main__":
    seed_universities()
