from database import SessionLocal, engine, Base
from models import University
import json

def seed_universities():
    db = SessionLocal()
    
    universities_data = [
        # The full list of 41 universities
        { "name": "Massachusetts Institute of Technology (MIT)", "country": "USA", "city": "Cambridge, MA", "ranking": 1, "programs": json.dumps(["Computer Science", "Engineering", "Business", "Data Science"]), "min_gpa": 3.7, "min_ielts": 7.0, "min_toefl": 100, "min_gre": 325, "min_gmat": None, "tuition_fee_min": 53000, "tuition_fee_max": 55000, "living_cost_yearly": 20000, "acceptance_rate": 4.0, "description": "World's leading university in technology and innovation", "website": "https://www.mit.edu" },
        { "name": "Stanford University", "country": "USA", "city": "Stanford, CA", "ranking": 2, "programs": json.dumps(["Computer Science", "MBA", "Engineering", "AI/ML"]), "min_gpa": 3.7, "min_ielts": 7.0, "min_toefl": 100, "min_gre": 325, "min_gmat": 730, "tuition_fee_min": 54000, "tuition_fee_max": 56000, "living_cost_yearly": 22000, "acceptance_rate": 3.9, "description": "Premier university for technology and entrepreneurship", "website": "https://www.stanford.edu" },
        { "name": "University of California, Berkeley", "country": "USA", "city": "Berkeley, CA", "ranking": 15, "programs": json.dumps(["Computer Science", "Engineering", "Business", "Data Science"]), "min_gpa": 3.5, "min_ielts": 7.0, "min_toefl": 90, "min_gre": 320, "min_gmat": None, "tuition_fee_min": 45000, "tuition_fee_max": 48000, "living_cost_yearly": 20000, "acceptance_rate": 15.0, "description": "Top public university with strong tech programs", "website": "https://www.berkeley.edu" },
        { "name": "Carnegie Mellon University", "country": "USA", "city": "Pittsburgh, PA", "ranking": 25, "programs": json.dumps(["Computer Science", "Robotics", "AI/ML", "Data Science"]), "min_gpa": 3.6, "min_ielts": 7.5, "min_toefl": 102, "min_gre": 322, "min_gmat": None, "tuition_fee_min": 50000, "tuition_fee_max": 52000, "living_cost_yearly": 18000, "acceptance_rate": 17.0, "description": "Best computer science and robotics programs", "website": "https://www.cmu.edu" },
        { "name": "Georgia Institute of Technology", "country": "USA", "city": "Atlanta, GA", "ranking": 38, "programs": json.dumps(["Computer Science", "Engineering", "Cybersecurity"]), "min_gpa": 3.3, "min_ielts": 7.0, "min_toefl": 90, "min_gre": 315, "tuition_fee_min": 31000, "tuition_fee_max": 33000, "living_cost_yearly": 15000, "acceptance_rate": 21.0, "description": "Top-tier engineering school with strong industry ties.", "website": "https://www.gatech.edu" },
        { "name": "Purdue University", "country": "USA", "city": "West Lafayette, IN", "ranking": 99, "programs": json.dumps(["Engineering", "Aviation", "Business"]), "min_gpa": 3.0, "min_ielts": 6.5, "min_toefl": 80, "min_gre": 310, "tuition_fee_min": 28000, "tuition_fee_max": 30000, "living_cost_yearly": 12000, "acceptance_rate": 60.0, "description": "Renowned for engineering and competitive tuition rates.", "website": "https://www.purdue.edu" },
        { "name": "University of Texas at Austin", "country": "USA", "city": "Austin, TX", "ranking": 40, "programs": json.dumps(["Computer Science", "Engineering", "Business"]), "min_gpa": 3.3, "min_ielts": 6.5, "min_toefl": 79, "min_gre": 315, "min_gmat": None, "tuition_fee_min": 38000, "tuition_fee_max": 40000, "living_cost_yearly": 15000, "acceptance_rate": 32.0, "description": "Strong public university with affordable tuition", "website": "https://www.utexas.edu" },
        { "name": "University of Michigan", "country": "USA", "city": "Ann Arbor, MI", "ranking": 25, "programs": json.dumps(["Business", "Engineering", "Law"]), "min_gpa": 3.5, "min_ielts": 7.0, "tuition_fee_min": 48000, "tuition_fee_max": 52000, "living_cost_yearly": 16000, "acceptance_rate": 20.0, "description": "Top-tier public research university.", "website": "https://www.umich.edu" },
        { "name": "Cornell University", "country": "USA", "city": "Ithaca, NY", "ranking": 20, "programs": json.dumps(["Engineering", "Hotel Management", "Computer Science"]), "min_gpa": 3.6, "min_ielts": 7.5, "tuition_fee_min": 58000, "tuition_fee_max": 62000, "living_cost_yearly": 18000, "acceptance_rate": 10.0, "description": "Ivy League member with a diverse range of majors.", "website": "https://www.cornell.edu" },
        
        { "name": "University of Oxford", "country": "UK", "city": "Oxford", "ranking": 3, "programs": json.dumps(["Computer Science", "Engineering", "Business", "Law"]), "min_gpa": 3.7, "min_ielts": 7.5, "min_toefl": 110, "min_gre": None, "min_gmat": None, "tuition_fee_min": 30000, "tuition_fee_max": 35000, "living_cost_yearly": 15000, "acceptance_rate": 17.5, "description": "One of the world's oldest and most prestigious universities", "website": "https://www.ox.ac.uk" },
        { "name": "University of Cambridge", "country": "UK", "city": "Cambridge", "ranking": 4, "programs": json.dumps(["Computer Science", "Engineering", "Mathematics", "Physics"]), "min_gpa": 3.7, "min_ielts": 7.5, "min_toefl": 110, "min_gre": None, "min_gmat": None, "tuition_fee_min": 30000, "tuition_fee_max": 35000, "living_cost_yearly": 14000, "acceptance_rate": 21.0, "description": "Historic university with world-class research", "website": "https://www.cam.ac.uk" },
        { "name": "Imperial College London", "country": "UK", "city": "London", "ranking": 8, "programs": json.dumps(["Engineering", "Computer Science", "Medicine", "Business"]), "min_gpa": 3.5, "min_ielts": 7.0, "min_toefl": 100, "min_gre": None, "min_gmat": None, "tuition_fee_min": 32000, "tuition_fee_max": 36000, "living_cost_yearly": 18000, "acceptance_rate": 14.0, "description": "Leading STEM university in London", "website": "https://www.imperial.ac.uk" },
        { "name": "University College London (UCL)", "country": "UK", "city": "London", "ranking": 9, "programs": json.dumps(["Computer Science", "Engineering", "Architecture", "Medicine"]), "min_gpa": 3.4, "min_ielts": 6.5, "min_toefl": 92, "min_gre": None, "min_gmat": None, "tuition_fee_min": 28000, "tuition_fee_max": 32000, "living_cost_yearly": 17000, "acceptance_rate": 48.0, "description": "Diverse and inclusive London university", "website": "https://www.ucl.ac.uk" },
        { "name": "King's College London", "country": "UK", "city": "London", "ranking": 35, "programs": json.dumps(["Medicine", "Law", "International Relations"]), "min_gpa": 3.3, "min_ielts": 7.0, "min_toefl": 100, "tuition_fee_min": 26000, "tuition_fee_max": 29000, "living_cost_yearly": 18000, "acceptance_rate": 13.0, "description": "Centrally located in London with global recognition.", "website": "https://www.kcl.ac.uk" },
        { "name": "University of Edinburgh", "country": "UK", "city": "Edinburgh", "ranking": 16, "programs": json.dumps(["Informatics", "Business", "Medicine"]), "min_gpa": 3.4, "min_ielts": 6.5, "min_toefl": 92, "tuition_fee_min": 24000, "tuition_fee_max": 28000, "living_cost_yearly": 12000, "acceptance_rate": 40.0, "description": "Historic Scottish institution known for informatics.", "website": "https://www.ed.ac.uk" },
        { "name": "University of Manchester", "country": "UK", "city": "Manchester", "ranking": 32, "programs": json.dumps(["Computer Science", "Engineering", "Business", "Medicine"]), "min_gpa": 3.2, "min_ielts": 6.5, "min_toefl": 80, "min_gre": None, "min_gmat": None, "tuition_fee_min": 25000, "tuition_fee_max": 28000, "living_cost_yearly": 12000, "acceptance_rate": 56.0, "description": "Large research university with diverse programs", "website": "https://www.manchester.ac.uk" },
        { "name": "University of Warwick", "country": "UK", "city": "Coventry", "ranking": 62, "programs": json.dumps(["Business", "Mathematics", "Sociology"]), "min_gpa": 3.2, "min_ielts": 6.5, "tuition_fee_min": 22000, "tuition_fee_max": 25000, "living_cost_yearly": 11000, "acceptance_rate": 14.0, "description": "Renowned business school and math programs.", "website": "https://warwick.ac.uk" },
        { "name": "University of Bristol", "country": "UK", "city": "Bristol", "ranking": 61, "programs": json.dumps(["Engineering", "Law", "Drama"]), "min_gpa": 3.1, "min_ielts": 6.5, "tuition_fee_min": 20000, "tuition_fee_max": 24000, "living_cost_yearly": 12000, "acceptance_rate": 60.0, "description": "Strong reputation for engineering and the arts.", "website": "https://www.bristol.ac.uk" },
        
        { "name": "University of Toronto", "country": "Canada", "city": "Toronto", "ranking": 18, "programs": json.dumps(["Computer Science", "Engineering", "Business", "Medicine"]), "min_gpa": 3.5, "min_ielts": 7.0, "min_toefl": 100, "min_gre": 320, "min_gmat": None, "tuition_fee_min": 35000, "tuition_fee_max": 40000, "living_cost_yearly": 15000, "acceptance_rate": 43.0, "description": "Canada's top university with strong research", "website": "https://www.utoronto.ca" },
        { "name": "University of British Columbia", "country": "Canada", "city": "Vancouver", "ranking": 34, "programs": json.dumps(["Computer Science", "Engineering", "Business", "Environmental Science"]), "min_gpa": 3.3, "min_ielts": 6.5, "min_toefl": 90, "min_gre": 315, "min_gmat": None, "tuition_fee_min": 32000, "tuition_fee_max": 36000, "living_cost_yearly": 14000, "acceptance_rate": 52.0, "description": "Beautiful campus with strong programs", "website": "https://www.ubc.ca" },
        { "name": "McGill University", "country": "Canada", "city": "Montreal", "ranking": 31, "programs": json.dumps(["Computer Science", "Engineering", "Medicine", "Law"]), "min_gpa": 3.3, "min_ielts": 6.5, "min_toefl": 90, "min_gre": 315, "min_gmat": None, "tuition_fee_min": 30000, "tuition_fee_max": 34000, "living_cost_yearly": 12000, "acceptance_rate": 46.0, "description": "Prestigious Canadian university with global reputation", "website": "https://www.mcgill.ca" },
        { "name": "University of Waterloo", "country": "Canada", "city": "Waterloo", "ranking": 112, "programs": json.dumps(["Computer Science", "Mathematics", "Engineering"]), "min_gpa": 3.2, "min_ielts": 6.5, "min_toefl": 90, "tuition_fee_min": 25000, "tuition_fee_max": 30000, "living_cost_yearly": 12000, "acceptance_rate": 53.0, "description": "Known for its co-op programs and strong tech focus.", "website": "https://uwaterloo.ca" },
        { "name": "University of Alberta", "country": "Canada", "city": "Edmonton", "ranking": 110, "programs": json.dumps(["Engineering", "AI", "Business"]), "min_gpa": 3.0, "min_ielts": 6.5, "min_toefl": 88, "tuition_fee_min": 22000, "tuition_fee_max": 25000, "living_cost_yearly": 11000, "acceptance_rate": 58.0, "description": "Leader in AI research and engineering.", "website": "https://www.ualberta.ca" },
        
        { "name": "Australian National University", "country": "Australia", "city": "Canberra", "ranking": 27, "programs": json.dumps(["Computer Science", "Engineering", "Business", "Political Science"]), "min_gpa": 3.3, "min_ielts": 6.5, "min_toefl": 80, "min_gre": None, "min_gmat": None, "tuition_fee_min": 35000, "tuition_fee_max": 40000, "living_cost_yearly": 18000, "acceptance_rate": 35.0, "description": "Australia's leading research university", "website": "https://www.anu.edu.au" },
        { "name": "University of Melbourne", "country": "Australia", "city": "Melbourne", "ranking": 33, "programs": json.dumps(["Computer Science", "Engineering", "Business", "Medicine"]), "min_gpa": 3.3, "min_ielts": 6.5, "min_toefl": 79, "min_gre": None, "min_gmat": None, "tuition_fee_min": 36000, "tuition_fee_max": 42000, "living_cost_yearly": 20000, "acceptance_rate": 70.0, "description": "Top Australian university with diverse programs", "website": "https://www.unimelb.edu.au" },
        { "name": "University of Sydney", "country": "Australia", "city": "Sydney", "ranking": 41, "programs": json.dumps(["Computer Science", "Engineering", "Business", "Architecture"]), "min_gpa": 3.2, "min_ielts": 6.5, "min_toefl": 85, "min_gre": None, "min_gmat": None, "tuition_fee_min": 34000, "tuition_fee_max": 40000, "living_cost_yearly": 19000, "acceptance_rate": 30.0, "description": "Historic university in vibrant Sydney", "website": "https://www.sydney.edu.au" },
        { "name": "University of Queensland", "country": "Australia", "city": "Brisbane", "ranking": 50, "programs": json.dumps(["Marine Biology", "Business", "Engineering"]), "min_gpa": 3.0, "min_ielts": 6.5, "min_toefl": 87, "tuition_fee_min": 32000, "tuition_fee_max": 37000, "living_cost_yearly": 17000, "acceptance_rate": 60.0, "description": "Beautiful campus known for research and biology.", "website": "https://www.uq.edu.au" },
        
        { "name": "Technical University of Munich", "country": "Germany", "city": "Munich", "ranking": 50, "programs": json.dumps(["Engineering", "Computer Science", "Physics", "Mathematics"]), "min_gpa": 3.0, "min_ielts": 6.5, "min_toefl": 88, "min_gre": None, "min_gmat": None, "tuition_fee_min": 0, "tuition_fee_max": 3000, "living_cost_yearly": 12000, "acceptance_rate": 8.0, "description": "Top German technical university with low tuition", "website": "https://www.tum.de" },
        { "name": "Ludwig Maximilian University of Munich", "country": "Germany", "city": "Munich", "ranking": 59, "programs": json.dumps(["Computer Science", "Physics", "Medicine", "Law"]), "min_gpa": 3.0, "min_ielts": 6.5, "min_toefl": 80, "min_gre": None, "min_gmat": None, "tuition_fee_min": 0, "tuition_fee_max": 3000, "living_cost_yearly": 11000, "acceptance_rate": 10.0, "description": "Prestigious German university with minimal fees", "website": "https://www.lmu.de" },
        { "name": "RWTH Aachen University", "country": "Germany", "city": "Aachen", "ranking": 106, "programs": json.dumps(["Engineering", "Computer Science", "Physics"]), "min_gpa": 2.8, "min_ielts": 6.0, "min_toefl": 80, "min_gre": None, "min_gmat": None, "tuition_fee_min": 0, "tuition_fee_max": 2000, "living_cost_yearly": 10000, "acceptance_rate": 10.0, "description": "Leading engineering university in Germany", "website": "https://www.rwth-aachen.de" },
        { "name": "TU Berlin", "country": "Germany", "city": "Berlin", "ranking": 147, "programs": json.dumps(["Engineering", "Architecture", "Computer Science"]), "min_gpa": 2.8, "min_ielts": 6.0, "min_toefl": 79, "tuition_fee_min": 0, "tuition_fee_max": 1000, "living_cost_yearly": 11000, "acceptance_rate": 20.0, "description": "Located in the capital, strong technical focus.", "website": "https://www.tu.berlin" },
        
        { "name": "National University of Singapore (NUS)", "country": "Singapore", "city": "Singapore", "ranking": 11, "programs": json.dumps(["Computer Science", "Engineering", "Business", "Medicine"]), "min_gpa": 3.7, "min_ielts": 7.0, "min_toefl": 100, "tuition_fee_min": 25000, "tuition_fee_max": 30000, "living_cost_yearly": 15000, "acceptance_rate": 5.0, "description": "Asia's leading university with global impact.", "website": "https://www.nus.edu.sg" },
        { "name": "Nanyang Technological University (NTU)", "country": "Singapore", "city": "Singapore", "ranking": 12, "programs": json.dumps(["Engineering", "Business", "Communications"]), "min_gpa": 3.6, "min_ielts": 6.5, "min_toefl": 95, "tuition_fee_min": 22000, "tuition_fee_max": 28000, "living_cost_yearly": 14000, "acceptance_rate": 10.0, "description": "Fastest-growing engineering focused university.", "website": "https://www.ntu.edu.sg" },
        
        { "name": "ETH Zurich", "country": "Switzerland", "city": "Zurich", "ranking": 6, "programs": json.dumps(["Engineering", "Physics", "Computer Science"]), "min_gpa": 3.8, "min_ielts": 7.0, "tuition_fee_min": 1500, "tuition_fee_max": 2000, "living_cost_yearly": 25000, "acceptance_rate": 27.0, "description": "World's top university for technical sciences.", "website": "https://ethz.ch" },
        { "name": "Tsinghua University", "country": "China", "city": "Beijing", "ranking": 16, "programs": json.dumps(["Engineering", "CS", "Natural Sciences"]), "min_gpa": 3.5, "min_ielts": 6.5, "tuition_fee_min": 5000, "tuition_fee_max": 8000, "living_cost_yearly": 6000, "acceptance_rate": 2.0, "description": "Leading technical university in China.", "website": "https://www.tsinghua.edu.cn" },
        { "name": "University of Tokyo", "country": "Japan", "city": "Tokyo", "ranking": 23, "programs": json.dumps(["Engineering", "Physics", "Humanities"]), "min_gpa": 3.4, "min_ielts": 6.5, "tuition_fee_min": 5000, "tuition_fee_max": 6000, "living_cost_yearly": 12000, "acceptance_rate": 30.0, "description": "Premier university in Japan.", "website": "https://www.u-tokyo.ac.jp" },
        { "name": "Yonsei University", "country": "South Korea", "city": "Seoul", "ranking": 73, "programs": json.dumps(["Business", "International Studies", "Engineering"]), "min_gpa": 3.2, "min_ielts": 6.0, "tuition_fee_min": 8000, "tuition_fee_max": 12000, "living_cost_yearly": 10000, "acceptance_rate": 35.0, "description": "Prestigious private university in Korea.", "website": "https://www.yonsei.ac.kr" },
        { "name": "Seoul National University", "country": "South Korea", "city": "Seoul", "ranking": 29, "programs": json.dumps(["Medicine", "Engineering", "Arts"]), "min_gpa": 3.5, "min_ielts": 6.5, "tuition_fee_min": 6000, "tuition_fee_max": 10000, "living_cost_yearly": 10000, "acceptance_rate": 15.0, "description": "The most prestigious public university in Korea.", "website": "https://www.snu.ac.kr" },
        { "name": "Hong Kong University of Science and Technology", "country": "Hong Kong", "city": "Hong Kong", "ranking": 34, "programs": json.dumps(["Engineering", "Business", "Science"]), "min_gpa": 3.3, "min_ielts": 6.5, "tuition_fee_min": 18000, "tuition_fee_max": 22000, "living_cost_yearly": 12000, "acceptance_rate": 18.0, "description": "Global powerhouse in engineering research.", "website": "https://hkust.edu.hk" },
        { "name": "University of Amsterdam", "country": "Netherlands", "city": "Amsterdam", "ranking": 55, "programs": json.dumps(["Psychology", "Economics", "AI"]), "min_gpa": 3.0, "min_ielts": 7.0, "tuition_fee_min": 15000, "tuition_fee_max": 18000, "living_cost_yearly": 14000, "acceptance_rate": 15.0, "description": "Broad research university in the Dutch capital.", "website": "https://www.uva.nl" }
    ]
    
    count = 0
    for uni_data in universities_data:
        # Check if exists by name
        exists = db.query(University).filter(University.name == uni_data["name"]).first()
        if not exists:
            university = University(**uni_data)
            db.add(university)
            count += 1
    
    db.commit()
    print(f"Successfully added {count} new universities! Total in DB: {db.query(University).count()}")
    db.close()

if __name__ == "__main__":
    Base.metadata.create_all(bind=engine)
    seed_universities()
